#################################################################
# Example render.yaml                                           #
# Do not use this file directly! Consult it for reference only. #
#################################################################

previews:
  generation: automatic # Enable preview environments

# List all services *except* PostgreSQL databases here
services:
  # A web service on the Python native runtime
  - type: web
    runtime: python
    name: request-holder
    repo: https://github.com/DaniloMrtz/request-holder # Default: Repo containing render.yaml
    numInstances: 1   # Manual scaling configuration. Default: 1 for new services
    region: ohio # Default: oregon
    plan: standard    # Default: starter
    branch: prod      # Default: master
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: false # Disable automatic deploys
    maxShutdownDelaySeconds: 300 # Increase graceful shutdown period. Default: 30, Max: 300
